<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<c:set var="pageTitle" value="Chi tiết đơn ứng tuyển | JobCV" scope="request" />
<jsp:include page="/WEB-INF/views/common/header.jsp" />

<div class="container-fluid candidate-shell"><div class="row g-0">
    <jsp:include page="/WEB-INF/views/common/candidate-sidebar.jsp" />
    <main class="candidate-main col-lg-9 col-xl-10">
        <jsp:include page="/WEB-INF/views/common/flash.jsp" />
        <c:choose>
            <c:when test="${not empty application}">
                <div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4"><div><nav aria-label="breadcrumb"><ol class="breadcrumb mb-2"><li class="breadcrumb-item"><a href="${pageContext.request.contextPath}/candidate/applications">Đơn ứng tuyển</a></li><li class="breadcrumb-item active" aria-current="page">Chi tiết</li></ol></nav><h1 class="page-title mb-1"><c:out value="${application.jobTitle}" /></h1><p class="text-muted mb-0">Mã đơn: #<c:out value="${application.id}" /> · Nộp ngày <c:out value="${application.appliedAt}" /></p></div><span class="status-badge status-${application.status} fs-6"><c:out value="${application.status}" /></span></div>
                <div class="row g-4">
                    <div class="col-xl-8">
                        <section class="content-card mb-4"><div class="d-flex flex-wrap justify-content-between gap-3"><div><h2 class="h5 fw-bold mb-3">Tổng quan đơn ứng tuyển</h2><dl class="row mb-0"><dt class="col-sm-4 text-muted fw-normal">Vị trí</dt><dd class="col-sm-8"><c:out value="${application.jobTitle}" /></dd><dt class="col-sm-4 text-muted fw-normal">Mã công việc</dt><dd class="col-sm-8"><c:out value="${application.jobCode}" /></dd><dt class="col-sm-4 text-muted fw-normal">Mức độ phù hợp</dt><dd class="col-sm-8"><span class="match-badge">Phù hợp <c:out value="${application.matchScore}" />%</span></dd><dt class="col-sm-4 text-muted fw-normal">CV đã dùng</dt><dd class="col-sm-8"><c:out value="${application.resumeFileName}" /></dd></dl></div><c:if test="${application.status eq 'SUBMITTED'}"><form action="${pageContext.request.contextPath}/candidate/applications/withdraw" method="post" data-confirm="Bạn có chắc muốn rút đơn ứng tuyển này? Hành động này không thể hoàn tác."><input type="hidden" name="applicationId" value="<c:out value='${application.id}'/>"><button class="btn btn-outline-danger" type="submit"><i class="bi bi-x-circle me-1"></i>Rút đơn</button></form></c:if></div><c:if test="${not empty application.coverLetter}"><div class="application-cover-letter mt-4"><span><i class="bi bi-chat-quote"></i></span><div><h3 class="h6">Lời giới thiệu đã gửi</h3><p><c:out value="${application.coverLetter}" /></p></div></div></c:if></section>
                        <section class="content-card mb-4"><h2 class="h5 fw-bold mb-3">Lịch sử trạng thái</h2><ol class="timeline"><c:forEach var="entry" items="${history}"><li class="timeline-item"><div class="d-flex flex-wrap justify-content-between gap-2"><div><span class="status-badge status-${entry.status}"><c:out value="${entry.status}" /></span><p class="mb-0 mt-2"><c:out value="${entry.note}" /></p></div><small class="text-muted"><c:out value="${entry.changedAt}" /></small></div><c:if test="${not empty entry.changedByName}"><small class="text-muted">Cập nhật bởi <c:out value="${entry.changedByName}" /></small></c:if></li></c:forEach><c:if test="${empty history}"><li class="timeline-item"><p class="text-muted mb-0">Chưa có lịch sử thay đổi trạng thái.</p></li></c:if></ol></section>
                        <section class="content-card"><h2 class="h5 fw-bold mb-3">Lịch phỏng vấn</h2><div class="vstack gap-3"><c:forEach var="interview" items="${interviews}"><article class="border rounded-3 p-3"><div class="d-flex flex-wrap justify-content-between gap-2"><div><h3 class="h6 fw-bold mb-1"><c:out value="${interview.type}" /></h3><p class="small text-muted mb-0"><i class="bi bi-calendar3 me-1"></i><c:out value="${interview.interviewDate}" /> · <c:out value="${interview.startTime}" /> – <c:out value="${interview.endTime}" /></p></div><span class="status-badge status-${interview.status}"><c:out value="${interview.status}" /></span></div><div class="small mt-3"><i class="bi bi-geo-alt me-1"></i><c:out value="${interview.location}" /></div><c:if test="${not empty interview.meetingUrl}"><a class="btn btn-sm btn-outline-primary mt-3" href="<c:out value='${interview.meetingUrl}'/>" target="_blank" rel="noopener"><i class="bi bi-camera-video me-1"></i>Vào phòng họp</a></c:if></article></c:forEach><c:if test="${empty interviews}"><p class="text-muted mb-0">Chưa có lịch phỏng vấn cho đơn này.</p></c:if></div></section>
                    </div>
                    <aside class="col-xl-4">
                        <section class="content-card mb-4"><h2 class="h5 fw-bold mb-3">Thư mời</h2><c:choose><c:when test="${not empty offer}"><div class="d-flex justify-content-between align-items-center mb-3"><span class="status-badge status-${offer.status}"><c:out value="${offer.status}" /></span><span class="small text-muted">Hết hạn: <c:out value="${offer.expiryDate}" /></span></div><dl class="row small"><dt class="col-5 text-muted fw-normal">Lương</dt><dd class="col-7 text-success fw-semibold"><fmt:formatNumber value="${offer.salary}" type="number" /> VNĐ</dd><dt class="col-5 text-muted fw-normal">Ngày bắt đầu</dt><dd class="col-7"><c:out value="${offer.startDate}" /></dd><dt class="col-5 text-muted fw-normal">Địa điểm</dt><dd class="col-7"><c:out value="${offer.location}" /></dd><dt class="col-5 text-muted fw-normal">Thử việc</dt><dd class="col-7"><c:out value="${offer.probationMonths}" /> tháng</dd></dl><c:if test="${not empty offer.note}"><p class="small text-muted border-top pt-3"><c:out value="${offer.note}" /></p></c:if><c:if test="${offer.status eq 'SENT'}"><div class="d-grid gap-2 mt-3"><form action="${pageContext.request.contextPath}/candidate/offers/respond" method="post" data-confirm="Bạn xác nhận chấp nhận thư mời này?"><input type="hidden" name="offerId" value="<c:out value='${offer.id}'/>"><button class="btn btn-success w-100" type="submit" name="response" value="ACCEPT" data-loading-button><i class="bi bi-check2-circle me-1"></i>Chấp nhận thư mời</button></form><form action="${pageContext.request.contextPath}/candidate/offers/respond" method="post" data-confirm="Bạn xác nhận từ chối thư mời này?"><input type="hidden" name="offerId" value="<c:out value='${offer.id}'/>"><button class="btn btn-outline-danger w-100" type="submit" name="response" value="DECLINE"><i class="bi bi-x-circle me-1"></i>Từ chối</button></form></div></c:if></c:when><c:otherwise><p class="text-muted small mb-0">Chưa có thư mời cho đơn ứng tuyển này.</p></c:otherwise></c:choose></section>
                        <section class="content-card"><h2 class="h5 fw-bold mb-3">Cần hỗ trợ?</h2><p class="small text-muted mb-0">Nếu bạn có thắc mắc về quy trình tuyển dụng, hãy liên hệ bộ phận Nhân sự qua kênh liên lạc được cung cấp trong lịch phỏng vấn.</p></section>
                    </aside>
                </div>
            </c:when>
            <c:otherwise><div class="rf-card empty-state"><div class="empty-icon"><i class="bi bi-file-earmark-x"></i></div><h1 class="h5">Không tìm thấy đơn ứng tuyển</h1><p class="mb-3">Đơn có thể không thuộc tài khoản của bạn hoặc không còn tồn tại.</p><a class="btn btn-primary" href="${pageContext.request.contextPath}/candidate/applications">Quay lại danh sách</a></div></c:otherwise>
        </c:choose>
    </main>
</div></div>
<jsp:include page="/WEB-INF/views/common/footer.jsp" />
