<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<c:set var="pageTitle" value="Tìm việc làm | JobCV" scope="request" />
<jsp:include page="/WEB-INF/views/common/header.jsp" />
<div class="container-fluid candidate-shell"><div class="row g-0"><jsp:include page="/WEB-INF/views/common/candidate-sidebar.jsp" />
<main class="candidate-main candidate-job-search col-lg-9 col-xl-10"><jsp:include page="/WEB-INF/views/common/flash.jsp" />
    <c:url var="createJobAlertUrl" value="/candidate/job-alerts"><c:param name="keyword" value="${param.keyword}"/><c:param name="departmentId" value="${param.departmentId}"/><c:param name="location" value="${param.location}"/><c:param name="employmentType" value="${param.employmentType}"/></c:url>
    <header class="portal-page-header"><div><span class="portal-kicker"><i class="bi bi-stars"></i> GỢI Ý THEO HỒ SƠ</span><h1 class="page-title">Cơ hội dành cho bạn</h1><p>Khám phá <strong><c:out value="${page.totalItems}" /></strong> vị trí và xem mức độ phù hợp được tính từ CV.</p></div><div class="d-flex flex-wrap gap-2"><a class="btn btn-outline-primary" href="${createJobAlertUrl}"><i class="bi bi-bell-plus me-1"></i>Lưu bộ lọc</a><a class="btn btn-primary" href="${pageContext.request.contextPath}/candidate/resumes"><i class="bi bi-file-earmark-person me-1"></i>Cập nhật CV</a></div></header>
    <form class="candidate-search-toolbar" action="${pageContext.request.contextPath}/candidate/jobs" method="get"><div class="candidate-search-keyword"><i class="bi bi-search"></i><label class="visually-hidden" for="candidateKeyword">Từ khóa</label><input id="candidateKeyword" name="keyword" type="search" maxlength="150" value="<c:out value='${param.keyword}'/>" placeholder="Tên vị trí, công ty hoặc kỹ năng"></div><div><label class="visually-hidden" for="candidateDepartment">Lĩnh vực</label><select class="form-select" id="candidateDepartment" name="departmentId"><option value="">Tất cả lĩnh vực</option><c:forEach var="department" items="${departments}"><option value="<c:out value='${department.id}'/>" ${param.departmentId eq department.id ? 'selected' : ''}><c:out value="${department.displayName}" /></option></c:forEach></select></div><div><label class="visually-hidden" for="candidateLocation">Địa điểm</label><input class="form-control" id="candidateLocation" name="location" maxlength="100" value="<c:out value='${param.location}'/>" placeholder="Địa điểm"></div><div><label class="visually-hidden" for="candidateEmploymentType">Loại hình</label><select class="form-select" id="candidateEmploymentType" name="employmentType"><option value="">Tất cả loại hình</option><option value="FULL_TIME" ${param.employmentType eq 'FULL_TIME' ? 'selected' : ''}>Toàn thời gian</option><option value="PART_TIME" ${param.employmentType eq 'PART_TIME' ? 'selected' : ''}>Bán thời gian</option><option value="INTERNSHIP" ${param.employmentType eq 'INTERNSHIP' ? 'selected' : ''}>Thực tập</option><option value="CONTRACT" ${param.employmentType eq 'CONTRACT' ? 'selected' : ''}>Hợp đồng</option><option value="REMOTE" ${param.employmentType eq 'REMOTE' ? 'selected' : ''}>Làm từ xa</option></select></div><button class="btn btn-primary" type="submit">Tìm việc</button></form>
    <div class="candidate-results-head"><div><h2>Việc làm phù hợp</h2><p>Kết quả ưu tiên theo điểm khớp kỹ năng trong CV.</p></div><div class="d-flex align-items-center gap-2"><span class="small text-muted">Sắp xếp</span><a class="filter-chip ${empty param.sort or param.sort eq 'newest' ? 'active' : ''}" href="?keyword=<c:out value='${param.keyword}'/>&sort=newest">Mới nhất</a><a class="filter-chip ${param.sort eq 'salary' ? 'active' : ''}" href="?keyword=<c:out value='${param.keyword}'/>&sort=salary">Lương cao</a></div></div>
    <div class="candidate-match-list"><c:forEach var="jobMatch" items="${page.items}"><c:set var="company" value="${companyById[jobMatch.job.companyId]}"/><c:url var="detailUrl" value="/jobs/detail"><c:param name="id" value="${jobMatch.job.id}" /></c:url><c:url var="companyUrl" value="/companies/detail"><c:param name="id" value="${jobMatch.job.companyId}" /></c:url><c:set var="jobIsSaved" value="${savedJobIds.contains(jobMatch.job.id)}"/>
        <article class="candidate-match-card"><a class="candidate-match-logo" href="${companyUrl}"><img src="${pageContext.request.contextPath}${company.uploadedLogo ? '/company-logo?id=' : '/assets/images/employers/'}${company.uploadedLogo ? company.id : company.logoFile}" alt="Logo ${company.name}"></a><div class="candidate-match-main"><div class="candidate-match-title-row"><div><a class="candidate-match-title" href="${detailUrl}"><c:out value="${jobMatch.job.title}" /></a><a class="candidate-match-company" href="${companyUrl}"><c:out value="${company.name}" /><i class="bi bi-patch-check-fill"></i></a></div><div class="candidate-score"><c:choose><c:when test="${hasCandidateResume}"><span><fmt:formatNumber value="${jobMatch.matchScore}" maxFractionDigits="0" />%</span><small>phù hợp</small></c:when><c:otherwise><span><i class="bi bi-file-earmark-plus"></i></span><small>thêm CV</small></c:otherwise></c:choose></div></div><div class="candidate-match-meta"><span class="salary"><i class="bi bi-cash-stack"></i><fmt:formatNumber value="${jobMatch.job.salaryMin}" type="number" />–<fmt:formatNumber value="${jobMatch.job.salaryMax}" type="number" /> VNĐ</span><span><i class="bi bi-geo-alt"></i><c:out value="${jobMatch.job.location}" /></span><span><i class="bi bi-briefcase"></i><span data-enum-label="${jobMatch.job.employmentType}"><c:out value="${jobMatch.job.employmentType}" /></span></span></div><div class="candidate-skill-match"><span>Kỹ năng khớp</span><div><c:forEach var="skill" items="${jobMatch.matchedSkills}" varStatus="loop"><em><i class="bi bi-check2"></i><c:out value="${skill}" /></em></c:forEach><c:if test="${empty jobMatch.matchedSkills}"><small>Hãy cập nhật thêm kỹ năng trong CV để nhận đánh giá chính xác hơn.</small></c:if></div></div><div class="candidate-match-footer"><span><i class="bi bi-clock"></i>Hạn nộp <c:out value="${jobMatch.job.deadline}" /></span><div><form action="${pageContext.request.contextPath}/candidate/saved-jobs/${jobIsSaved ? 'remove' : 'save'}" method="post"><input type="hidden" name="jobId" value="<c:out value='${jobMatch.job.id}'/>"><input type="hidden" name="returnTo" value="/candidate/jobs"><button class="btn btn-sm ${jobIsSaved ? 'btn-primary' : 'btn-outline-primary'}" type="submit" aria-label="${jobIsSaved ? 'Bỏ lưu' : 'Lưu việc'}"><i class="bi ${jobIsSaved ? 'bi-bookmark-heart-fill' : 'bi-bookmark-heart'}"></i></button></form><a class="btn btn-sm btn-outline-primary" href="${detailUrl}">Chi tiết</a><a class="btn btn-sm btn-primary" href="${detailUrl}#apply-now">Ứng tuyển</a></div></div></div></article>
    </c:forEach><c:if test="${empty page.items}"><div class="rf-card empty-state"><div class="empty-icon"><i class="bi bi-search"></i></div><h2 class="h5">Chưa có công việc phù hợp</h2><p class="mb-3">Thử thay đổi từ khóa hoặc cập nhật CV để hệ thống hiểu bạn tốt hơn.</p><div class="d-flex justify-content-center gap-2"><a class="btn btn-outline-primary" href="${pageContext.request.contextPath}/candidate/jobs">Xóa bộ lọc</a><a class="btn btn-primary" href="${pageContext.request.contextPath}/candidate/resumes">Cập nhật CV</a></div></div></c:if></div>
    <c:set var="paginationPath" value="/candidate/jobs" scope="request" /><jsp:include page="/WEB-INF/views/common/pagination.jsp" />
</main></div></div>
<jsp:include page="/WEB-INF/views/common/footer.jsp" />
