<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<c:set var="pageTitle" value="Tìm việc làm | RecruitFlow" scope="request" />
<jsp:include page="/WEB-INF/views/common/header.jsp" />

<div class="container-fluid candidate-shell"><div class="row g-0">
    <jsp:include page="/WEB-INF/views/common/candidate-sidebar.jsp" />
    <main class="candidate-main col-lg-9 col-xl-10">
        <jsp:include page="/WEB-INF/views/common/flash.jsp" />
        <div class="d-flex flex-wrap justify-content-between gap-3 mb-4"><div><h1 class="page-title mb-1">Tìm việc làm</h1><p class="text-muted mb-0">Khám phá các vị trí đang mở và xem mức độ phù hợp với CV của bạn.</p></div><a class="btn btn-outline-primary" href="${pageContext.request.contextPath}/candidate/resumes"><i class="bi bi-file-earmark-person me-1"></i>Cập nhật CV</a></div>
        <form class="filter-card mb-4" action="${pageContext.request.contextPath}/candidate/jobs" method="get"><div class="row g-3 align-items-end"><div class="col-lg-3"><label class="form-label fw-semibold" for="candidateKeyword">Từ khóa</label><input class="form-control" id="candidateKeyword" name="keyword" type="search" value="<c:out value='${param.keyword}'/>" placeholder="Tên vị trí hoặc kỹ năng"></div><div class="col-md-4 col-lg-2"><label class="form-label fw-semibold" for="candidateDepartment">Phòng ban</label><select class="form-select" id="candidateDepartment" name="departmentId"><option value="">Tất cả</option><c:forEach var="department" items="${departments}"><option value="<c:out value='${department.id}'/>" ${param.departmentId eq department.id ? 'selected' : ''}><c:out value="${department.name}" /></option></c:forEach></select></div><div class="col-md-4 col-lg-2"><label class="form-label fw-semibold" for="candidateLocation">Địa điểm</label><input class="form-control" id="candidateLocation" name="location" value="<c:out value='${param.location}'/>" placeholder="Hà Nội, Remote..."></div><div class="col-md-4 col-lg-3"><label class="form-label fw-semibold" for="candidateEmploymentType">Loại hình</label><select class="form-select" id="candidateEmploymentType" name="employmentType"><option value="">Tất cả</option><option value="FULL_TIME" ${param.employmentType eq 'FULL_TIME' ? 'selected' : ''}>Toàn thời gian</option><option value="PART_TIME" ${param.employmentType eq 'PART_TIME' ? 'selected' : ''}>Bán thời gian</option><option value="INTERNSHIP" ${param.employmentType eq 'INTERNSHIP' ? 'selected' : ''}>Thực tập</option><option value="CONTRACT" ${param.employmentType eq 'CONTRACT' ? 'selected' : ''}>Hợp đồng</option><option value="REMOTE" ${param.employmentType eq 'REMOTE' ? 'selected' : ''}>Remote</option></select></div><div class="col-md-4 col-lg-2 d-grid"><button class="btn btn-primary" type="submit"><i class="bi bi-search me-1"></i>Tìm kiếm</button></div></div></form>
        <div class="row g-4"><c:forEach var="jobMatch" items="${page.items}"><c:url var="candidateJobDetailUrl" value="/jobs/detail"><c:param name="id" value="${jobMatch.job.id}" /></c:url><div class="col-md-6 col-xxl-4"><article class="job-card"><div class="d-flex justify-content-between align-items-start gap-2"><span class="badge text-bg-primary-subtle text-primary"><c:out value="${jobMatch.job.departmentName}" /></span><span class="match-badge">Match <c:out value="${jobMatch.matchScore}" />%</span></div><a class="job-card-title d-block mt-3 mb-2" href="${candidateJobDetailUrl}"><c:out value="${jobMatch.job.title}" /></a><div class="d-flex flex-column gap-2"><span class="meta-item"><i class="bi bi-geo-alt"></i><c:out value="${jobMatch.job.location}" /></span><span class="meta-item"><i class="bi bi-briefcase"></i><c:out value="${jobMatch.job.employmentType}" /></span><span class="meta-item"><i class="bi bi-calendar3"></i>Hạn: <c:out value="${jobMatch.job.deadline}" /></span></div><div class="small text-muted mt-3">Kỹ năng khớp: <c:forEach var="skill" items="${jobMatch.matchedSkills}" varStatus="loop"><c:out value="${skill}" /><c:if test="${not loop.last}">, </c:if></c:forEach><c:if test="${empty jobMatch.matchedSkills}">Chưa có kỹ năng khớp</c:if></div><div class="d-flex justify-content-between align-items-center gap-2 pt-3 mt-3 border-top"><span class="fw-semibold text-success small"><fmt:formatNumber value="${jobMatch.job.salaryMin}" type="number" /> – <fmt:formatNumber value="${jobMatch.job.salaryMax}" type="number" /> VNĐ</span><div class="d-flex gap-2"><a class="btn btn-sm btn-outline-primary" href="${candidateJobDetailUrl}">Chi tiết</a><form action="${pageContext.request.contextPath}/candidate/applications/apply" method="post" data-confirm="Bạn muốn ứng tuyển vị trí này bằng CV mặc định?"><input type="hidden" name="jobId" value="<c:out value='${jobMatch.job.id}'/>"><button class="btn btn-sm btn-primary" type="submit" data-loading-button>Ứng tuyển</button></form></div></div></article></div></c:forEach><c:if test="${empty page.items}"><div class="col-12"><div class="rf-card empty-state"><div class="empty-icon"><i class="bi bi-search"></i></div><h2 class="h5">Không có việc làm phù hợp</h2><p class="mb-3">Bạn có thể cập nhật CV hoặc thử thay đổi bộ lọc.</p><a class="btn btn-outline-primary" href="${pageContext.request.contextPath}/candidate/resumes">Cập nhật CV</a></div></div></c:if></div>
        <jsp:include page="/WEB-INF/views/common/pagination.jsp" />
    </main>
</div></div>
<jsp:include page="/WEB-INF/views/common/footer.jsp" />
