/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.120
 * Generated at: 2026-08-23 10:27:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.candidate;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class cv_002dbuilder_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.LinkedHashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1786374896000L));
    _jspx_dependants.put("jar:file:/C:/Users/Admin/Documents/GitHub/JobCV/.recruitflow/tomcat-base/webapps/recruitflow/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"container-fluid candidate-shell\">\n");
      out.write("    <div class=\"row g-0\">\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/candidate-sidebar.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("        <main class=\"candidate-main col-lg-9 col-xl-10\">\n");
      out.write("            ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/flash.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("            <div class=\"d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4\">\n");
      out.write("                <div>\n");
      out.write("                    <p class=\"text-primary text-uppercase small fw-bold mb-1\">CV Builder</p>\n");
      out.write("                    <h1 class=\"page-title mb-1\">Tạo CV theo mẫu</h1>\n");
      out.write("                    <p class=\"text-muted mb-0\">Chọn mẫu, điền thông tin thật của bạn và tạo CV DOCX có thể dùng ngay khi ứng tuyển.</p>\n");
      out.write("                </div>\n");
      out.write("                <a class=\"btn btn-outline-primary\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/candidate/resumes\">\n");
      out.write("                    <i class=\"bi bi-folder2-open me-1\"></i>CV của tôi\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <section class=\"content-card cv-builder-intro mb-4\">\n");
      out.write("                <div class=\"row align-items-center g-3\">\n");
      out.write("                    <div class=\"col-lg\">\n");
      out.write("                        <h2 class=\"h5 fw-bold mb-2\">3 mẫu CV sẵn sàng cho ứng tuyển</h2>\n");
      out.write("                        <p class=\"text-muted mb-0\">CV sẽ được tạo dưới dạng DOCX, lưu trong khu vực CV của bạn và có thể chọn làm CV mặc định.</p>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-lg-auto\">\n");
      out.write("                        <span class=\"badge text-bg-light border text-dark px-3 py-2\"><i class=\"bi bi-shield-check text-success me-1\"></i>Không tự nộp đơn thay bạn</span>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </section>\n");
      out.write("\n");
      out.write("            <form id=\"cvBuilderForm\" method=\"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/candidate/cv-builder/create\" class=\"row g-4\">\n");
      out.write("                <input id=\"cvTemplateInput\" type=\"hidden\" name=\"template\" value=\"MODERN\">\n");
      out.write("\n");
      out.write("                <div class=\"col-xl-8\">\n");
      out.write("                    <section class=\"content-card mb-4\">\n");
      out.write("                        <div class=\"d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3\">\n");
      out.write("                            <div>\n");
      out.write("                                <h2 class=\"h5 fw-bold mb-1\">1. Chọn mẫu CV</h2>\n");
      out.write("                                <p class=\"small text-muted mb-0\">Bạn có thể xem trước và đổi mẫu trước khi tạo.</p>\n");
      out.write("                            </div>\n");
      out.write("                            <span class=\"small text-muted\"><i class=\"bi bi-file-earmark-word me-1\"></i>Xuất DOCX</span>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"row g-3\" role=\"radiogroup\" aria-label=\"Mẫu CV\">\n");
      out.write("                            <div class=\"col-md-4\">\n");
      out.write("                                <button type=\"button\" class=\"cv-template-card is-selected w-100\" data-cv-template=\"MODERN\" role=\"radio\" aria-checked=\"true\">\n");
      out.write("                                    <span class=\"cv-template-preview modern\"><span></span><strong>NGUYỄN MINH AN</strong><small>Backend Developer</small><i></i><b></b></span>\n");
      out.write("                                    <strong class=\"d-block mt-3\">Hiện đại</strong>\n");
      out.write("                                    <small class=\"text-muted\">Gọn gàng, có điểm nhấn màu xanh</small>\n");
      out.write("                                </button>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-md-4\">\n");
      out.write("                                <button type=\"button\" class=\"cv-template-card w-100\" data-cv-template=\"CLASSIC\" role=\"radio\" aria-checked=\"false\">\n");
      out.write("                                    <span class=\"cv-template-preview classic\"><strong>NGUYỄN MINH AN</strong><small>Backend Developer</small><i></i><b></b></span>\n");
      out.write("                                    <strong class=\"d-block mt-3\">Chuyên nghiệp</strong>\n");
      out.write("                                    <small class=\"text-muted\">Trang trọng, phù hợp doanh nghiệp</small>\n");
      out.write("                                </button>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-md-4\">\n");
      out.write("                                <button type=\"button\" class=\"cv-template-card w-100\" data-cv-template=\"MINIMAL\" role=\"radio\" aria-checked=\"false\">\n");
      out.write("                                    <span class=\"cv-template-preview minimal\"><strong>Nguyễn Minh An</strong><small>Backend Developer</small><i></i><b></b></span>\n");
      out.write("                                    <strong class=\"d-block mt-3\">Tối giản</strong>\n");
      out.write("                                    <small class=\"text-muted\">Tập trung vào nội dung và kỹ năng</small>\n");
      out.write("                                </button>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </section>\n");
      out.write("\n");
      out.write("                    <section class=\"content-card mb-4\">\n");
      out.write("                        <h2 class=\"h5 fw-bold mb-3\">2. Thông tin liên hệ</h2>\n");
      out.write("                        <div class=\"row g-3\">\n");
      out.write("                            <div class=\"col-md-6\">\n");
      out.write("                                <label class=\"form-label\" for=\"cvFullName\">Họ và tên <span class=\"text-danger\">*</span></label>\n");
      out.write("                                <input class=\"form-control\" id=\"cvFullName\" name=\"fullName\" required maxlength=\"100\" data-cv-preview=\"name\"\n");
      out.write("                                       value=\"");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("\" placeholder=\"Nguyễn Văn A\">\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-md-6\">\n");
      out.write("                                <label class=\"form-label\" for=\"cvTargetRole\">Vị trí mục tiêu <span class=\"text-danger\">*</span></label>\n");
      out.write("                                <input class=\"form-control\" id=\"cvTargetRole\" name=\"targetRole\" required maxlength=\"120\" data-cv-preview=\"role\"\n");
      out.write("                                       placeholder=\"Ví dụ: Java Backend Developer\">\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-md-6\">\n");
      out.write("                                <label class=\"form-label\" for=\"cvEmail\">Email</label>\n");
      out.write("                                <input class=\"form-control\" id=\"cvEmail\" name=\"email\" type=\"email\" maxlength=\"254\" data-cv-preview=\"email\"\n");
      out.write("                                       value=\"");
      if (_jspx_meth_c_005fout_005f1(_jspx_page_context))
        return;
      out.write("\" placeholder=\"email@example.com\">\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-md-3\">\n");
      out.write("                                <label class=\"form-label\" for=\"cvPhone\">Số điện thoại</label>\n");
      out.write("                                <input class=\"form-control\" id=\"cvPhone\" name=\"phone\" maxlength=\"30\" data-cv-preview=\"phone\" placeholder=\"09xx xxx xxx\">\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-md-3\">\n");
      out.write("                                <label class=\"form-label\" for=\"cvLocation\">Địa điểm</label>\n");
      out.write("                                <input class=\"form-control\" id=\"cvLocation\" name=\"location\" maxlength=\"120\" data-cv-preview=\"location\"\n");
      out.write("                                       value=\"");
      if (_jspx_meth_c_005fout_005f2(_jspx_page_context))
        return;
      out.write("\" placeholder=\"Hà Nội\">\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </section>\n");
      out.write("\n");
      out.write("                    <section class=\"content-card mb-4\">\n");
      out.write("                        <h2 class=\"h5 fw-bold mb-3\">3. Nội dung CV</h2>\n");
      out.write("                        <div class=\"mb-3\">\n");
      out.write("                            <label class=\"form-label\" for=\"cvSummary\">Giới thiệu ngắn <span class=\"text-danger\">*</span></label>\n");
      out.write("                            <textarea class=\"form-control\" id=\"cvSummary\" name=\"summary\" rows=\"4\" required maxlength=\"2000\" data-cv-preview=\"summary\"\n");
      out.write("                                      placeholder=\"Tóm tắt năng lực, mục tiêu nghề nghiệp và giá trị bạn có thể mang lại.\">");
      if (_jspx_meth_c_005fout_005f3(_jspx_page_context))
        return;
      out.write("</textarea>\n");
      out.write("                            <div class=\"form-text\">Viết ngắn gọn, trung thực và bám sát vị trí mục tiêu.</div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"mb-3\">\n");
      out.write("                            <label class=\"form-label\" for=\"cvExperience\">Kinh nghiệm làm việc</label>\n");
      out.write("                            <textarea class=\"form-control\" id=\"cvExperience\" name=\"experience\" rows=\"5\" maxlength=\"6000\" data-cv-preview=\"experience\"\n");
      out.write("                                      placeholder=\"2024 – nay | Công ty ABC | Java Intern&#10;Phát triển REST API, viết unit test và tối ưu truy vấn MySQL.\"></textarea>\n");
      out.write("                            <div class=\"form-text\">Mỗi dòng sẽ trở thành một gạch đầu dòng trong CV.</div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"mb-3\">\n");
      out.write("                            <label class=\"form-label\" for=\"cvEducation\">Học vấn</label>\n");
      out.write("                            <textarea class=\"form-control\" id=\"cvEducation\" name=\"education\" rows=\"3\" maxlength=\"4000\" data-cv-preview=\"education\"\n");
      out.write("                                      placeholder=\"2021 – 2025 | Đại học ABC | Công nghệ thông tin&#10;Chuyên ngành: Kỹ thuật phần mềm\"></textarea>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"mb-3\">\n");
      out.write("                            <label class=\"form-label\" for=\"cvSkills\">Kỹ năng</label>\n");
      out.write("                            <textarea class=\"form-control\" id=\"cvSkills\" name=\"skills\" rows=\"3\" maxlength=\"2000\" data-cv-preview=\"skills\"\n");
      out.write("                                      placeholder=\"Java, Spring Boot, JDBC, MySQL, Git, REST API\">");
      if (_jspx_meth_c_005fout_005f4(_jspx_page_context))
        return;
      out.write("</textarea>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"mb-3\">\n");
      out.write("                            <label class=\"form-label\" for=\"cvProjects\">Dự án nổi bật</label>\n");
      out.write("                            <textarea class=\"form-control\" id=\"cvProjects\" name=\"projects\" rows=\"4\" maxlength=\"5000\" data-cv-preview=\"projects\"\n");
      out.write("                                      placeholder=\"RecruitFlow | Java Servlet, JSP, MySQL&#10;Xây dựng quy trình tuyển dụng, phân quyền và quản lý onboarding.\"></textarea>\n");
      out.write("                        </div>\n");
      out.write("                        <div>\n");
      out.write("                            <label class=\"form-label\" for=\"cvCertifications\">Chứng chỉ / hoạt động</label>\n");
      out.write("                            <textarea class=\"form-control\" id=\"cvCertifications\" name=\"certifications\" rows=\"3\" maxlength=\"3000\" data-cv-preview=\"certifications\"\n");
      out.write("                                      placeholder=\"TOEIC 800 | AWS Cloud Practitioner | Thành viên CLB lập trình\"></textarea>\n");
      out.write("                        </div>\n");
      out.write("                    </section>\n");
      out.write("\n");
      out.write("                    <section class=\"content-card d-flex flex-wrap justify-content-between align-items-center gap-3\">\n");
      out.write("                        <div class=\"form-check mb-0\">\n");
      out.write("                            <input class=\"form-check-input\" type=\"checkbox\" name=\"makeDefault\" value=\"true\" id=\"makeDefault\" checked>\n");
      out.write("                            <label class=\"form-check-label\" for=\"makeDefault\">Đặt CV vừa tạo làm CV mặc định</label>\n");
      out.write("                        </div>\n");
      out.write("                        <button class=\"btn btn-primary px-4\" type=\"submit\" data-loading-button>\n");
      out.write("                            <i class=\"bi bi-file-earmark-plus me-1\"></i>Tạo CV DOCX\n");
      out.write("                        </button>\n");
      out.write("                    </section>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <aside class=\"col-xl-4\">\n");
      out.write("                    <div class=\"cv-live-preview sticky-xl-top\" style=\"top: 5.5rem;\">\n");
      out.write("                        <div class=\"d-flex justify-content-between align-items-center mb-3\">\n");
      out.write("                            <h2 class=\"h6 fw-bold mb-0\"><i class=\"bi bi-eye me-1\"></i>Xem trước nội dung</h2>\n");
      out.write("                            <span class=\"badge text-bg-light border text-dark\" id=\"previewTemplateLabel\">Hiện đại</span>\n");
      out.write("                        </div>\n");
      out.write("                        <article class=\"cv-paper cv-paper-modern\" id=\"cvLivePaper\">\n");
      out.write("                            <header>\n");
      out.write("                                <h3 id=\"previewName\">");
      if (_jspx_meth_c_005fout_005f5(_jspx_page_context))
        return;
      out.write("</h3>\n");
      out.write("                                <p id=\"previewRole\">Vị trí mục tiêu</p>\n");
      out.write("                                <small id=\"previewContact\">Email · Số điện thoại · Địa điểm</small>\n");
      out.write("                            </header>\n");
      out.write("                            <section>\n");
      out.write("                                <h4>GIỚI THIỆU</h4>\n");
      out.write("                                <p id=\"previewSummary\">Hãy tóm tắt năng lực, mục tiêu nghề nghiệp và điểm mạnh của bạn.</p>\n");
      out.write("                            </section>\n");
      out.write("                            <section>\n");
      out.write("                                <h4>KINH NGHIỆM</h4>\n");
      out.write("                                <p id=\"previewExperience\">Kinh nghiệm làm việc của bạn sẽ hiển thị tại đây.</p>\n");
      out.write("                            </section>\n");
      out.write("                            <section>\n");
      out.write("                                <h4>KỸ NĂNG</h4>\n");
      out.write("                                <p id=\"previewSkills\">Các kỹ năng chuyên môn phù hợp vị trí.</p>\n");
      out.write("                            </section>\n");
      out.write("                        </article>\n");
      out.write("                        <p class=\"small text-muted mt-3 mb-0\"><i class=\"bi bi-info-circle me-1\"></i>Bản xem trước chỉ để định hướng bố cục; file DOCX sẽ chứa toàn bộ phần bạn điền.</p>\n");
      out.write("                    </div>\n");
      out.write("                </aside>\n");
      out.write("            </form>\n");
      out.write("        </main>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("    (function () {\n");
      out.write("        function textOrFallback(value, fallback) {\n");
      out.write("            return value && value.trim() ? value.trim() : fallback;\n");
      out.write("        }\n");
      out.write("        function updateContact() {\n");
      out.write("            var parts = ['email', 'phone', 'location'].map(function (key) {\n");
      out.write("                var field = document.querySelector('[data-cv-preview=\"' + key + '\"]');\n");
      out.write("                return field ? field.value.trim() : '';\n");
      out.write("            }).filter(Boolean);\n");
      out.write("            document.getElementById('previewContact').textContent = parts.length ? parts.join(' · ') : 'Email · Số điện thoại · Địa điểm';\n");
      out.write("        }\n");
      out.write("        function updatePreview(event) {\n");
      out.write("            var field = event.target;\n");
      out.write("            var key = field.dataset.cvPreview;\n");
      out.write("            if (!key) return;\n");
      out.write("            var targets = {\n");
      out.write("                name: ['previewName', 'Họ và tên'],\n");
      out.write("                role: ['previewRole', 'Vị trí mục tiêu'],\n");
      out.write("                summary: ['previewSummary', 'Hãy tóm tắt năng lực, mục tiêu nghề nghiệp và điểm mạnh của bạn.'],\n");
      out.write("                experience: ['previewExperience', 'Kinh nghiệm làm việc của bạn sẽ hiển thị tại đây.'],\n");
      out.write("                skills: ['previewSkills', 'Các kỹ năng chuyên môn phù hợp vị trí.']\n");
      out.write("            };\n");
      out.write("            if (targets[key]) {\n");
      out.write("                document.getElementById(targets[key][0]).textContent = textOrFallback(field.value, targets[key][1]);\n");
      out.write("            }\n");
      out.write("            if (key === 'email' || key === 'phone' || key === 'location') updateContact();\n");
      out.write("        }\n");
      out.write("        document.querySelectorAll('[data-cv-preview]').forEach(function (field) {\n");
      out.write("            field.addEventListener('input', updatePreview);\n");
      out.write("        });\n");
      out.write("        document.querySelectorAll('[data-cv-template]').forEach(function (button) {\n");
      out.write("            button.addEventListener('click', function () {\n");
      out.write("                var template = button.dataset.cvTemplate;\n");
      out.write("                document.getElementById('cvTemplateInput').value = template;\n");
      out.write("                document.querySelectorAll('[data-cv-template]').forEach(function (card) {\n");
      out.write("                    var selected = card === button;\n");
      out.write("                    card.classList.toggle('is-selected', selected);\n");
      out.write("                    card.setAttribute('aria-checked', String(selected));\n");
      out.write("                });\n");
      out.write("                var paper = document.getElementById('cvLivePaper');\n");
      out.write("                paper.className = 'cv-paper cv-paper-' + template.toLowerCase();\n");
      out.write("                document.getElementById('previewTemplateLabel').textContent = {\n");
      out.write("                    MODERN: 'Hiện đại', CLASSIC: 'Chuyên nghiệp', MINIMAL: 'Tối giản'\n");
      out.write("                }[template];\n");
      out.write("            });\n");
      out.write("        });\n");
      out.write("        updateContact();\n");
      out.write("    }());\n");
      out.write("</script>\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/candidate/cv-builder.jsp(3,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("pageTitle");
      // /WEB-INF/views/candidate/cv-builder.jsp(3,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/candidate/cv-builder.jsp(3,0) 'Tạo CV theo mẫu | RecruitFlow'",_jsp_getExpressionFactory().createValueExpression("Tạo CV theo mẫu | RecruitFlow",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/candidate/cv-builder.jsp(3,0) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setScope("request");
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent(null);
      // /WEB-INF/views/candidate/cv-builder.jsp(79,46) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.fullName}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent(null);
      // /WEB-INF/views/candidate/cv-builder.jsp(89,46) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.email}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f2_reused = false;
    try {
      _jspx_th_c_005fout_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f2.setParent(null);
      // /WEB-INF/views/candidate/cv-builder.jsp(98,46) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profile.address}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f2 = _jspx_th_c_005fout_005f2.doStartTag();
      if (_jspx_th_c_005fout_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
      _jspx_th_c_005fout_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f3 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f3_reused = false;
    try {
      _jspx_th_c_005fout_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f3.setParent(null);
      // /WEB-INF/views/candidate/cv-builder.jsp(108,123) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profile.summary}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f3 = _jspx_th_c_005fout_005f3.doStartTag();
      if (_jspx_th_c_005fout_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f3);
      _jspx_th_c_005fout_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f4 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f4_reused = false;
    try {
      _jspx_th_c_005fout_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f4.setParent(null);
      // /WEB-INF/views/candidate/cv-builder.jsp(125,98) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f4.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profile.skills}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f4 = _jspx_th_c_005fout_005f4.doStartTag();
      if (_jspx_th_c_005fout_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f4);
      _jspx_th_c_005fout_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f5 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f5_reused = false;
    try {
      _jspx_th_c_005fout_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f5.setParent(null);
      // /WEB-INF/views/candidate/cv-builder.jsp(158,53) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f5.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.fullName}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f5 = _jspx_th_c_005fout_005f5.doStartTag();
      if (_jspx_th_c_005fout_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f5);
      _jspx_th_c_005fout_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f5_reused);
    }
    return false;
  }
}
