<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<c:set var="pageTitle" value="Việc làm đang tuyển | RecruitFlow" scope="request" />
<jsp:include page="/WEB-INF/views/common/header.jsp" />
<jsp:include page="/WEB-INF/views/common/navbar.jsp" />

<main class="job-search-page">
    <section class="job-search-hero"><div class="container"><nav aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="${pageContext.request.contextPath}/">Trang chủ</a></li><li class="breadcrumb-item active">Việc làm</li></ol></nav><span class="section-kicker">CƠ HỘI NGHỀ NGHIỆP</span><h1>Tìm công việc phù hợp với bạn</h1><p><strong><c:out value="${page.totalItems}" /></strong> vị trí đang mở từ các nhà tuyển dụng đã xác thực.</p>
        <form class="job-search-bar" action="${pageContext.request.contextPath}/jobs" method="get" data-loading-form><div class="job-suggest-field"><i class="bi bi-search"></i><label class="visually-hidden" for="keyword">Từ khóa</label><input id="keyword" name="keyword" type="search" autocomplete="off" data-job-suggest-url="${pageContext.request.contextPath}/jobs/suggestions" maxlength="150" value="<c:out value='${keyword}'/>" placeholder="Chức danh, kỹ năng hoặc tên công ty"></div><div><i class="bi bi-geo-alt"></i><label class="visually-hidden" for="location">Địa điểm</label><input id="location" name="location" maxlength="100" value="<c:out value='${location}'/>" placeholder="Địa điểm làm việc"></div><button class="btn btn-primary" type="submit" data-loading-button><i class="bi bi-search me-1"></i>Tìm việc</button></form>
        <div class="job-quick-search"><span>Gợi ý:</span><a href="${pageContext.request.contextPath}/jobs?keyword=Java">Java Developer</a><a href="${pageContext.request.contextPath}/jobs?keyword=Marketing">Marketing</a><a href="${pageContext.request.contextPath}/jobs?employmentType=INTERNSHIP">Thực tập</a><a href="${pageContext.request.contextPath}/jobs?employmentType=REMOTE">Remote</a></div>
    </div></section>
    <section class="public-section"><div class="container"><jsp:include page="/WEB-INF/views/common/flash.jsp" />
        <button class="btn btn-outline-primary job-filter-mobile-toggle" type="button" data-filter-toggle aria-expanded="false" aria-controls="jobFilterPanel"><i class="bi bi-sliders me-1"></i>Bộ lọc nâng cao</button>
        <div class="job-search-layout">
            <aside class="job-filter-panel" id="jobFilterPanel"><div class="job-filter-head"><div><i class="bi bi-sliders"></i><strong>Bộ lọc tìm kiếm</strong></div><button type="button" class="job-filter-close" data-filter-close aria-label="Đóng bộ lọc"><i class="bi bi-x-lg"></i></button><a href="${pageContext.request.contextPath}/jobs">Xóa lọc</a></div><form action="${pageContext.request.contextPath}/jobs" method="get" data-loading-form><input type="hidden" name="keyword" value="<c:out value='${keyword}'/>"><input type="hidden" name="location" value="<c:out value='${location}'/>">
                <div class="job-filter-group"><label for="departmentId">Lĩnh vực</label><select class="form-select" id="departmentId" name="departmentId"><option value="">Tất cả lĩnh vực</option><c:forEach var="department" items="${departments}"><option value="<c:out value='${department.id}'/>" ${departmentId eq department.id ? 'selected' : ''}><c:out value="${department.displayName}" /></option></c:forEach></select></div>
                <div class="job-filter-group"><label for="categoryId">Chuyên môn</label><select class="form-select" id="categoryId" name="categoryId"><option value="">Tất cả chuyên môn</option><c:forEach var="category" items="${categories}"><option value="<c:out value='${category.id}'/>" ${categoryId eq category.id ? 'selected' : ''}><c:out value="${category.name}" /></option><c:forEach var="child" items="${category.children}"><option value="<c:out value='${child.id}'/>" ${categoryId eq child.id ? 'selected' : ''}>— <c:out value="${child.name}" /></option></c:forEach></c:forEach></select></div>
                <div class="job-filter-group"><label for="employmentType">Loại hình làm việc</label><select class="form-select" id="employmentType" name="employmentType"><option value="">Tất cả loại hình</option><option value="FULL_TIME" ${employmentType eq 'FULL_TIME' ? 'selected' : ''}>Toàn thời gian</option><option value="PART_TIME" ${employmentType eq 'PART_TIME' ? 'selected' : ''}>Bán thời gian</option><option value="INTERNSHIP" ${employmentType eq 'INTERNSHIP' ? 'selected' : ''}>Thực tập</option><option value="CONTRACT" ${employmentType eq 'CONTRACT' ? 'selected' : ''}>Hợp đồng</option><option value="REMOTE" ${employmentType eq 'REMOTE' ? 'selected' : ''}>Làm từ xa</option></select></div>
                <div class="job-filter-group"><span class="job-filter-label">Mức lương (VNĐ/tháng)</span><div class="job-filter-range"><div><label class="visually-hidden" for="salaryMin">Từ</label><input class="form-control" id="salaryMin" name="salaryMin" type="number" min="0" step="1000000" value="<c:out value='${salaryMin}'/>" placeholder="Từ"></div><span>–</span><div><label class="visually-hidden" for="salaryMax">Đến</label><input class="form-control" id="salaryMax" name="salaryMax" type="number" min="0" step="1000000" value="<c:out value='${salaryMax}'/>" placeholder="Đến"></div></div></div>
                <div class="job-filter-group"><span class="job-filter-label">Kinh nghiệm</span><div class="job-filter-range"><div><label class="visually-hidden" for="experienceMin">Từ</label><select class="form-select" id="experienceMin" name="experienceMin"><option value="">Từ</option><option value="0" ${experienceMin eq 0 ? 'selected' : ''}>0 năm</option><option value="1" ${experienceMin eq 1 ? 'selected' : ''}>1 năm</option><option value="2" ${experienceMin eq 2 ? 'selected' : ''}>2 năm</option><option value="3" ${experienceMin eq 3 ? 'selected' : ''}>3 năm</option><option value="5" ${experienceMin eq 5 ? 'selected' : ''}>5 năm</option></select></div><span>–</span><div><label class="visually-hidden" for="experienceMax">Đến</label><select class="form-select" id="experienceMax" name="experienceMax"><option value="">Đến</option><option value="0" ${experienceMax eq 0 ? 'selected' : ''}>0 năm</option><option value="1" ${experienceMax eq 1 ? 'selected' : ''}>1 năm</option><option value="2" ${experienceMax eq 2 ? 'selected' : ''}>2 năm</option><option value="3" ${experienceMax eq 3 ? 'selected' : ''}>3 năm</option><option value="5" ${experienceMax eq 5 ? 'selected' : ''}>5 năm</option><option value="10" ${experienceMax eq 10 ? 'selected' : ''}>10 năm</option></select></div></div></div>
                <button class="btn btn-primary w-100" type="submit" data-loading-button>Áp dụng bộ lọc</button>
            </form><div class="job-alert-promo"><span><i class="bi bi-bell"></i></span><strong>Không bỏ lỡ việc phù hợp</strong><p>Đăng nhập để lưu bộ lọc và nhận thông báo cơ hội mới.</p><a href="${pageContext.request.contextPath}/login">Thiết lập thông báo <i class="bi bi-arrow-right"></i></a></div></aside>
            <div class="job-results-panel"><header class="job-results-head"><div><h2><c:choose><c:when test="${not empty keyword}">Kết quả cho “<c:out value="${keyword}" />”</c:when><c:otherwise>Việc làm mới nhất</c:otherwise></c:choose></h2><p>Tìm thấy <strong><c:out value="${page.totalItems}" /></strong> cơ hội phù hợp</p></div><form action="${pageContext.request.contextPath}/jobs" method="get"><input type="hidden" name="keyword" value="<c:out value='${keyword}'/>"><input type="hidden" name="departmentId" value="<c:out value='${departmentId}'/>"><input type="hidden" name="categoryId" value="<c:out value='${categoryId}'/>"><input type="hidden" name="location" value="<c:out value='${location}'/>"><input type="hidden" name="employmentType" value="<c:out value='${employmentType}'/>"><input type="hidden" name="salaryMin" value="<c:out value='${salaryMin}'/>"><input type="hidden" name="salaryMax" value="<c:out value='${salaryMax}'/>"><input type="hidden" name="experienceMin" value="<c:out value='${experienceMin}'/>"><input type="hidden" name="experienceMax" value="<c:out value='${experienceMax}'/>"><label for="sort">Sắp xếp</label><select class="form-select form-select-sm" id="sort" name="sort" onchange="this.form.submit()"><option value="newest" ${sort eq 'newest' ? 'selected' : ''}>Mới nhất</option><option value="deadline" ${sort eq 'deadline' ? 'selected' : ''}>Sắp hết hạn</option><option value="salary" ${sort eq 'salary' ? 'selected' : ''}>Lương cao</option><option value="experience" ${sort eq 'experience' ? 'selected' : ''}>Ít kinh nghiệm</option></select></form></header>
                <c:if test="${not empty keyword or not empty location or not empty departmentId or not empty categoryId or not empty employmentType or not empty salaryMin or not empty salaryMax or not empty experienceMin or not empty experienceMax}"><div class="active-filter-chips" aria-label="Bộ lọc đang áp dụng"><span><i class="bi bi-funnel"></i>Đang lọc:</span><c:if test="${not empty keyword}"><b><c:out value="${keyword}" /></b></c:if><c:if test="${not empty location}"><b><c:out value="${location}" /></b></c:if><c:if test="${not empty employmentType}"><b data-enum-label="${employmentType}"><c:out value="${employmentType}" /></b></c:if><c:if test="${not empty salaryMin or not empty salaryMax}"><b>Lương <fmt:formatNumber value="${salaryMin}" type="number" />–<fmt:formatNumber value="${salaryMax}" type="number" /></b></c:if><c:if test="${not empty experienceMin or not empty experienceMax}"><b>Kinh nghiệm ${experienceMin}–${experienceMax} năm</b></c:if><a href="${pageContext.request.contextPath}/jobs">Xóa tất cả</a></div></c:if>
                <div class="job-result-list"><c:forEach var="job" items="${page.items}"><c:url var="jobDetailUrl" value="/jobs/detail"><c:param name="id" value="${job.id}" /></c:url><c:url var="companyUrl" value="/companies/detail"><c:param name="id" value="${job.companyId}" /></c:url>
                    <article class="job-result-card"><a class="job-result-logo" href="${companyUrl}"><img src="${pageContext.request.contextPath}/companies/media?id=${job.companyId}&type=logo" alt="Logo ${job.companyName}" loading="lazy"></a><div class="job-result-main"><div class="d-flex flex-wrap justify-content-between gap-2"><div><a class="job-result-title" href="${jobDetailUrl}"><c:out value="${job.title}" /></a><a class="job-result-company" href="${companyUrl}"><c:out value="${empty job.companyName ? job.departmentName : job.companyName}" /><c:if test="${not empty job.companyId}"><i class="bi bi-patch-check-fill"></i></c:if></a></div><div class="job-result-card-actions"><span class="job-new-badge">Mới</span><c:if test="${sessionScope.role eq 'CANDIDATE'}"><form action="${pageContext.request.contextPath}/candidate/saved-jobs/${savedJobIds.contains(job.id) ? 'remove' : 'save'}" method="post"><input type="hidden" name="jobId" value="${job.id}"><input type="hidden" name="returnTo" value="/jobs"><button type="submit" class="job-list-save ${savedJobIds.contains(job.id) ? 'is-saved' : ''}" aria-label="${savedJobIds.contains(job.id) ? 'Bỏ lưu' : 'Lưu'} ${job.title}"><i class="bi ${savedJobIds.contains(job.id) ? 'bi-bookmark-fill' : 'bi-bookmark'}"></i></button></form></c:if></div></div><div class="job-result-tags"><span class="salary"><i class="bi bi-cash-stack"></i><fmt:formatNumber value="${job.salaryMin}" type="number" />–<fmt:formatNumber value="${job.salaryMax}" type="number" /> VNĐ</span><span><i class="bi bi-geo-alt"></i><c:out value="${job.location}" /></span><span><i class="bi bi-briefcase"></i><span data-enum-label="${job.employmentType}"><c:out value="${job.employmentType}" /></span></span><span><i class="bi bi-person-workspace"></i><c:out value="${job.experienceRequired}" /> năm</span><c:if test="${not empty job.categoryName}"><span><i class="bi bi-tags"></i><c:out value="${job.categoryName}" /></span></c:if></div><div class="job-result-bottom"><span><i class="bi bi-clock"></i>Hạn nộp <fmt:formatDate value="${job.deadline}" pattern="dd/MM/yyyy" /></span><span><i class="bi bi-people"></i>Tuyển <c:out value="${job.numberOfPositions}" /> vị trí</span><div><a class="btn btn-sm btn-outline-primary" href="${jobDetailUrl}">Xem chi tiết</a><c:choose><c:when test="${sessionScope.role eq 'CANDIDATE'}"><a class="btn btn-sm btn-primary" href="${jobDetailUrl}#apply-now">Ứng tuyển</a></c:when><c:when test="${empty sessionScope.userId}"><a class="btn btn-sm btn-primary" href="${pageContext.request.contextPath}/login">Đăng nhập để ứng tuyển</a></c:when></c:choose></div></div></div></article>
                </c:forEach><c:if test="${empty page.items}"><div class="rf-card empty-state"><div class="empty-icon"><i class="bi bi-search"></i></div><h3 class="h5">Chưa tìm thấy công việc phù hợp</h3><p class="mb-3">Thử rút gọn từ khóa, chọn lĩnh vực khác hoặc xóa bộ lọc.</p><a class="btn btn-outline-primary" href="${pageContext.request.contextPath}/jobs">Xem tất cả việc làm</a></div></c:if></div>
                <jsp:include page="/WEB-INF/views/common/pagination.jsp" />
            </div>
        </div>
    </div></section>
</main>
<jsp:include page="/WEB-INF/views/common/footer.jsp" />
