<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<c:set var="pageTitle" value="Offer của tôi | RecruitFlow" scope="request" />
<jsp:include page="/WEB-INF/views/common/header.jsp" />

<div class="container-fluid candidate-shell"><div class="row g-0">
    <jsp:include page="/WEB-INF/views/common/candidate-sidebar.jsp" />
    <main class="candidate-main col-lg-9 col-xl-10">
        <jsp:include page="/WEB-INF/views/common/flash.jsp" />
        <div class="mb-4"><h1 class="page-title mb-1">Offer của tôi</h1><p class="text-muted mb-0">Xem kỹ điều khoản offer trước khi đưa ra quyết định.</p></div>
        <div class="row g-4"><c:forEach var="offer" items="${offers}"><div class="col-xl-6"><article class="content-card h-100"><div class="d-flex flex-wrap justify-content-between align-items-start gap-2 mb-3"><div><span class="badge text-bg-primary-subtle text-primary mb-2"><c:out value="${offer.departmentName}" /></span><h2 class="h4 fw-bold mb-0"><c:out value="${offer.jobTitle}" /></h2></div><span class="status-badge status-${offer.status}"><c:out value="${offer.status}" /></span></div><div class="border rounded-3 p-3 bg-light mb-3"><div class="text-muted small">Mức lương đề xuất</div><div class="h4 text-success fw-bold mb-0"><fmt:formatNumber value="${offer.salary}" type="number" /> VNĐ</div></div><dl class="row small"><dt class="col-5 text-muted fw-normal">Ngày bắt đầu</dt><dd class="col-7"><c:out value="${offer.startDate}" /></dd><dt class="col-5 text-muted fw-normal">Thời gian thử việc</dt><dd class="col-7"><c:out value="${offer.probationMonths}" /> tháng</dd><dt class="col-5 text-muted fw-normal">Địa điểm</dt><dd class="col-7"><c:out value="${offer.location}" /></dd><dt class="col-5 text-muted fw-normal">Phản hồi trước</dt><dd class="col-7"><c:out value="${offer.expiryDate}" /></dd></dl><c:if test="${not empty offer.note}"><div class="small text-muted border-top pt-3" style="white-space: pre-line;"><c:out value="${offer.note}" /></div></c:if><c:if test="${offer.status eq 'SENT'}"><div class="row g-2 mt-3"><div class="col-sm-6"><form action="${pageContext.request.contextPath}/candidate/offers/respond" method="post" data-confirm="Bạn xác nhận chấp nhận offer này? Sau khi chấp nhận, quy trình onboarding sẽ được tạo."><input type="hidden" name="offerId" value="<c:out value='${offer.id}'/>"><button class="btn btn-success w-100" type="submit" name="response" value="ACCEPT" data-loading-button><i class="bi bi-check2-circle me-1"></i>Chấp nhận</button></form></div><div class="col-sm-6"><form action="${pageContext.request.contextPath}/candidate/offers/respond" method="post" data-confirm="Bạn xác nhận từ chối offer này?"><input type="hidden" name="offerId" value="<c:out value='${offer.id}'/>"><button class="btn btn-outline-danger w-100" type="submit" name="response" value="DECLINE"><i class="bi bi-x-circle me-1"></i>Từ chối</button></form></div></div></c:if></article></div></c:forEach><c:if test="${empty offers}"><div class="col-12"><div class="rf-card empty-state"><div class="empty-icon"><i class="bi bi-envelope-paper"></i></div><h2 class="h5">Bạn chưa có offer nào</h2><p class="mb-0">Offer sẽ hiển thị tại đây khi bạn hoàn thành các vòng tuyển dụng.</p></div></div></c:if></div>
    </main>
</div></div>
<jsp:include page="/WEB-INF/views/common/footer.jsp" />
