<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<c:set var="pageTitle" value="Banner trang chủ | JobCV" scope="request" />
<jsp:include page="/WEB-INF/views/common/header.jsp" />
<div class="container-fluid p-0"><div class="row g-0"><jsp:include page="/WEB-INF/views/common/admin-sidebar.jsp" />
<main class="col-md-10 offset-md-2 bg-light min-vh-100"><div class="topbar"><div><p class="text-muted small mb-1">Quản trị hệ thống</p><h4 class="mb-0">Banner trang chủ</h4></div></div>
<div class="main-content"><jsp:include page="/WEB-INF/views/common/flash.jsp" /><c:if test="${not empty error}"><div class="alert alert-danger"><c:out value="${error}" /></div></c:if>
<div class="row g-4"><div class="col-xl-4"><section class="card shadow-sm border-0"><div class="card-body p-4"><h5>Thêm ảnh banner</h5><p class="text-muted small">Bạn có thể chọn một hoặc nhiều ảnh. Mỗi ảnh tối đa 2 MB, hỗ trợ JPG, PNG, WEBP.</p>
<form method="post" action="${pageContext.request.contextPath}/admin/home-banners" enctype="multipart/form-data" data-validate-form><div class="mb-3"><label class="form-label" for="bannerFiles">Ảnh banner <span class="text-danger">*</span></label><input class="form-control" id="bannerFiles" name="bannerFiles" type="file" accept="image/jpeg,image/png,image/webp" multiple required><div class="form-text">Ảnh ngang tỷ lệ 16:5 hoặc 16:6 sẽ hiển thị đẹp nhất.</div></div><div class="mb-3"><label class="form-label" for="bannerTitle">Tiêu đề phủ trên ảnh</label><input class="form-control" id="bannerTitle" name="title" maxlength="120" placeholder="Ví dụ: Khám phá việc làm IT"></div><div class="mb-3"><label class="form-label" for="bannerSubtitle">Mô tả ngắn</label><input class="form-control" id="bannerSubtitle" name="subtitle" maxlength="300" placeholder="Nội dung hiển thị tùy chọn"></div><div class="mb-3"><label class="form-label" for="bannerTargetUrl">Nút/link khi nhấn ảnh</label><input class="form-control" id="bannerTargetUrl" name="targetUrl" maxlength="500" placeholder="/jobs?keyword=Intern%20Backend"><div class="form-text">Chỉ dùng đường dẫn nội bộ, ví dụ /jobs, /companies hoặc /candidate/jobs.</div></div><div class="row g-3 align-items-end"><div class="col-6"><label class="form-label" for="bannerOrder">Thứ tự</label><input class="form-control" id="bannerOrder" name="displayOrder" type="number" min="0" max="10000" value="0"></div><div class="col-6"><div class="form-check form-switch mb-2"><input class="form-check-input" id="bannerActive" name="active" type="checkbox" value="true" checked><label class="form-check-label" for="bannerActive">Hiển thị ngay</label></div></div></div><button class="btn btn-primary w-100 mt-4" type="submit" data-loading-button><i class="bi bi-cloud-arrow-up me-1"></i>Tải banner lên</button></form>
</div></section></div>
<div class="col-xl-8"><section class="card shadow-sm border-0"><div class="card-header bg-white border-0 px-4 pt-4"><h5 class="mb-1">Banner đang quản lý</h5><small class="text-muted">Kéo thứ tự bằng cách sửa “Thứ tự”; tắt hiển thị để giữ ảnh nhưng không đưa ra trang chủ.</small></div><div class="card-body p-4 pt-3"><div class="row g-3">
<c:forEach var="banner" items="${homeBanners}"><div class="col-md-6"><article class="home-banner-admin-card"><img src="${pageContext.request.contextPath}/home-banner?id=${banner.id}" alt="Banner #${banner.id}"><div class="p-3"><div class="d-flex justify-content-between align-items-start gap-2"><div><strong><c:out value="${empty banner.title ? 'Banner chưa có tiêu đề' : banner.title}" /></strong><small class="d-block text-muted text-truncate"><c:out value="${empty banner.targetUrl ? 'Không có liên kết khi nhấn' : banner.targetUrl}" /></small></div><span class="badge ${banner.active ? 'text-bg-success' : 'text-bg-secondary'}">${banner.active ? 'Đang hiện' : 'Đã ẩn'}</span></div><div class="d-flex gap-2 mt-3"><button class="btn btn-sm btn-outline-primary edit-home-banner" type="button" data-id="${banner.id}" data-title="<c:out value='${banner.title}'/>" data-subtitle="<c:out value='${banner.subtitle}'/>" data-target-url="<c:out value='${banner.targetUrl}'/>" data-display-order="${banner.displayOrder}" data-active="${banner.active}" data-bs-toggle="modal" data-bs-target="#homeBannerEditModal"><i class="bi bi-pencil"></i> Chỉnh sửa</button><form method="post" action="${pageContext.request.contextPath}/admin/home-banners/delete" onsubmit="return confirm('Xóa banner này? Ảnh sẽ bị xóa khỏi máy chủ.');"><input type="hidden" name="id" value="${banner.id}"><button class="btn btn-sm btn-outline-danger" type="submit"><i class="bi bi-trash"></i></button></form></div></div></article></div></c:forEach>
<c:if test="${empty homeBanners}"><div class="col-12 py-5 text-center text-muted"><i class="bi bi-images d-block fs-2 mb-2"></i>Chưa có banner. Tải ảnh đầu tiên để hiển thị trên trang chủ.</div></c:if>
</div></div></section></div></div></div></main></div></div>
<div class="modal fade" id="homeBannerEditModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog"><div class="modal-content"><form method="post" action="${pageContext.request.contextPath}/admin/home-banners/update"><div class="modal-header"><h5 class="modal-title">Chỉnh sửa banner</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><input id="editBannerId" name="id" type="hidden"><div class="mb-3"><label class="form-label" for="editBannerTitle">Tiêu đề</label><input class="form-control" id="editBannerTitle" name="title" maxlength="120"></div><div class="mb-3"><label class="form-label" for="editBannerSubtitle">Mô tả</label><input class="form-control" id="editBannerSubtitle" name="subtitle" maxlength="300"></div><div class="mb-3"><label class="form-label" for="editBannerTarget">Liên kết khi nhấn</label><input class="form-control" id="editBannerTarget" name="targetUrl" maxlength="500" placeholder="/jobs"></div><div class="row g-3"><div class="col-6"><label class="form-label" for="editBannerOrder">Thứ tự</label><input class="form-control" id="editBannerOrder" name="displayOrder" type="number" min="0" max="10000"></div><div class="col-6 d-flex align-items-end"><div class="form-check form-switch mb-2"><input class="form-check-input" id="editBannerActive" name="active" type="checkbox" value="true"><label class="form-check-label" for="editBannerActive">Hiển thị</label></div></div></div></div><div class="modal-footer"><button class="btn btn-light" type="button" data-bs-dismiss="modal">Hủy</button><button class="btn btn-primary" type="submit"><i class="bi bi-save me-1"></i>Lưu thay đổi</button></div></form></div></div></div>
<script>(function(){document.querySelectorAll('.edit-home-banner').forEach(function(button){button.addEventListener('click',function(){document.getElementById('editBannerId').value=button.dataset.id;document.getElementById('editBannerTitle').value=button.dataset.title||'';document.getElementById('editBannerSubtitle').value=button.dataset.subtitle||'';document.getElementById('editBannerTarget').value=button.dataset.targetUrl||'';document.getElementById('editBannerOrder').value=button.dataset.displayOrder||0;document.getElementById('editBannerActive').checked=button.dataset.active==='true';});});}());</script>
<jsp:include page="/WEB-INF/views/common/footer.jsp" />
