<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<c:set var="pageTitle" value="Báo cáo nền tảng | RecruitFlow"/><jsp:include page="/WEB-INF/views/common/header.jsp"/>
<div class="app-layout"><jsp:include page="/WEB-INF/views/common/admin-sidebar.jsp"/><main class="app-main bg-light"><div class="topbar"><div><p class="text-muted small mb-1">Dữ liệu toàn hệ thống</p><h1 class="h4 mb-0">Báo cáo tuyển dụng</h1></div><span class="platform-data-badge"><i class="bi bi-shield-check"></i>Dữ liệu thật</span></div><div class="main-content"><c:if test="${not empty error}"><div class="alert alert-danger"><c:out value="${error}"/></div></c:if>
<section class="card mb-4"><div class="card-body"><form class="row g-3 align-items-end" action="${pageContext.request.contextPath}/admin/reports" method="get"><div class="col-md-4"><label class="form-label" for="adminReportFrom">Từ ngày</label><input class="form-control" id="adminReportFrom" type="date" name="fromDate" value="<c:out value='${param.fromDate}'/>"></div><div class="col-md-4"><label class="form-label" for="adminReportTo">Đến ngày</label><input class="form-control" id="adminReportTo" type="date" name="toDate" value="<c:out value='${param.toDate}'/>"></div><div class="col-md-4"><button class="btn btn-primary" type="submit"><i class="bi bi-bar-chart me-1"></i>Cập nhật báo cáo</button></div></form></div></section>
<div class="row g-3 mb-4"><div class="col-sm-6 col-xl-3"><article class="admin-kpi"><span class="admin-kpi-icon admin-blue"><i class="bi bi-file-earmark-person"></i></span><div><small>Tổng hồ sơ</small><strong><c:out value="${report.totalApplications}"/></strong><em>Trong khoảng đã chọn</em></div></article></div><div class="col-sm-6 col-xl-3"><article class="admin-kpi"><span class="admin-kpi-icon admin-violet"><i class="bi bi-person-lines-fill"></i></span><div><small>Danh sách ngắn</small><strong><c:out value="${report.shortlistRate}"/>%</strong><em>Tỷ lệ chuyển đổi</em></div></article></div><div class="col-sm-6 col-xl-3"><article class="admin-kpi"><span class="admin-kpi-icon admin-amber"><i class="bi bi-envelope-paper"></i></span><div><small>Thư mời đã gửi</small><strong><c:out value="${report.offersSent}"/></strong><em>Offer trong hệ thống</em></div></article></div><div class="col-sm-6 col-xl-3"><article class="admin-kpi"><span class="admin-kpi-icon admin-green"><i class="bi bi-person-check"></i></span><div><small>Tỷ lệ tuyển</small><strong><c:out value="${report.hireRate}"/>%</strong><em>Đã tuyển / tổng hồ sơ</em></div></article></div></div>
<div class="row g-4"><div class="col-xl-7"><section class="admin-panel h-100"><header class="admin-panel-header"><div><span>PHỄU TUYỂN DỤNG</span><h2>Chuyển đổi ứng viên</h2></div></header><div class="vstack gap-3">
<div><div class="d-flex justify-content-between mb-1"><span>Đã nộp hồ sơ</span><strong><c:out value="${report.applied}"/></strong></div><div class="progress"><div class="progress-bar" style="width:${report.applied gt 0 ? 100 : 0}%"></div></div></div>
<div><div class="d-flex justify-content-between mb-1"><span>Đang sàng lọc</span><strong><c:out value="${report.screening}"/></strong></div><div class="progress"><div class="progress-bar" style="width:${report.applied gt 0 ? report.screening * 100 / report.applied : 0}%"></div></div></div>
<div><div class="d-flex justify-content-between mb-1"><span>Đã phỏng vấn</span><strong><c:out value="${report.interviewed}"/></strong></div><div class="progress"><div class="progress-bar" style="width:${report.applied gt 0 ? report.interviewed * 100 / report.applied : 0}%"></div></div></div>
<div><div class="d-flex justify-content-between mb-1"><span>Đã gửi thư mời</span><strong><c:out value="${report.offered}"/></strong></div><div class="progress"><div class="progress-bar" style="width:${report.applied gt 0 ? report.offered * 100 / report.applied : 0}%"></div></div></div>
<div><div class="d-flex justify-content-between mb-1"><span>Đã tuyển</span><strong><c:out value="${report.hired}"/></strong></div><div class="progress"><div class="progress-bar" style="width:${report.applied gt 0 ? report.hired * 100 / report.applied : 0}%"></div></div></div>
</div></section></div><div class="col-xl-5"><section class="admin-panel h-100"><header class="admin-panel-header"><div><span>THEO THÁNG</span><h2>Lượng hồ sơ</h2></div></header><div class="admin-month-list"><c:forEach var="entry" items="${report.applicationsByMonth}"><div><span><c:out value="${entry.key}"/></span><strong><c:out value="${entry.value}"/></strong></div></c:forEach><c:if test="${empty report.applicationsByMonth}"><div class="admin-audit-empty"><i class="bi bi-bar-chart"></i><strong>Chưa có dữ liệu</strong><small>Hồ sơ mới sẽ được tổng hợp tại đây.</small></div></c:if></div></section></div></div>
</div></main></div><jsp:include page="/WEB-INF/views/common/footer.jsp"/>
