<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<c:set var="pageTitle" value="Quản lý người dùng | RecruitFlow" />
<jsp:include page="/WEB-INF/views/common/header.jsp" />

<div class="container-fluid p-0">
    <div class="row g-0">
        <jsp:include page="/WEB-INF/views/common/admin-sidebar.jsp" />
        <main class="col-md-10 offset-md-2 bg-light min-vh-100">
            <div class="topbar"><div><p class="text-muted small mb-1">Quản trị hệ thống</p><h4 class="mb-0">Quản lý người dùng</h4></div><span class="text-muted small">Khóa/mở khóa chỉ có hiệu lực sau lần xác thực tiếp theo.</span></div>
            <div class="main-content">
                <jsp:include page="/WEB-INF/views/common/flash.jsp" />
                <c:if test="${not empty sessionScope.successMessage}"><div class="alert alert-success alert-dismissible fade show" role="alert"><c:out value="${sessionScope.successMessage}" /><button class="btn-close" type="button" data-bs-dismiss="alert"></button></div><c:remove var="successMessage" scope="session" /></c:if>
                <c:if test="${not empty sessionScope.error}"><div class="alert alert-danger alert-dismissible fade show" role="alert"><c:out value="${sessionScope.error}" /><button class="btn-close" type="button" data-bs-dismiss="alert"></button></div><c:remove var="error" scope="session" /></c:if>
                <section class="card mb-4"><div class="card-body"><form class="row gy-2 gx-3 align-items-end" method="get" action="${pageContext.request.contextPath}/admin/users"><div class="col-lg-5"><label class="form-label small text-muted">Tìm kiếm</label><input class="form-control" name="keyword" value="<c:out value='${param.keyword}'/>" placeholder="Họ tên hoặc email"></div><div class="col-lg-2"><label class="form-label small text-muted">Vai trò</label><select class="form-select" name="role"><option value="">Tất cả vai trò</option><option value="ADMIN">ADMIN</option><option value="HR">HR</option><option value="INTERVIEWER">INTERVIEWER</option><option value="CANDIDATE">CANDIDATE</option></select></div><div class="col-lg-3"><label class="form-label small text-muted">Trạng thái</label><select class="form-select" name="status"><option value="">Tất cả trạng thái</option><option value="ACTIVE">ACTIVE</option><option value="LOCKED">LOCKED</option><option value="INACTIVE">INACTIVE</option></select></div><div class="col-lg-2 d-flex gap-2"><button class="btn btn-outline-primary flex-grow-1" type="submit"><i class="bi bi-search"></i> Lọc</button><a class="btn btn-light" href="${pageContext.request.contextPath}/admin/users"><i class="bi bi-arrow-counterclockwise"></i></a></div></form></div></section>
                <section class="card"><div class="card-header bg-white border-0 px-4 pt-4"><h5 class="mb-1">Danh sách tài khoản</h5><small class="text-muted">Mọi thay đổi trạng thái tài khoản được ghi nhận trong nhật ký hệ thống.</small></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead class="table-light"><tr><th class="ps-4">Người dùng</th><th>Vai trò</th><th>Trạng thái</th><th>Ngày tạo</th><th class="text-end pe-4">Thao tác</th></tr></thead><tbody>
                    <c:forEach var="user" items="${users}"><tr><td class="ps-4"><div class="fw-semibold"><c:out value="${user.fullName}" /></div><small class="text-muted"><c:out value="${user.email}" /></small></td><td><c:choose><c:when test="${user.id eq sessionScope.userId}"><span class="badge text-bg-light border"><c:out value="${user.roleName}" /></span></c:when><c:otherwise><form method="post" action="${pageContext.request.contextPath}/admin/users/role" class="d-flex gap-1 align-items-center"><input type="hidden" name="userId" value="${user.id}"><select class="form-select form-select-sm" name="roleId" aria-label="Vai trò"><c:forEach var="role" items="${roles}"><option value="${role.id}" ${role.roleName eq user.roleName ? 'selected' : ''}><c:out value="${role.roleName}" /></option></c:forEach></select><button class="btn btn-sm btn-outline-primary" type="submit" title="Lưu vai trò"><i class="bi bi-check2"></i></button></form></c:otherwise></c:choose></td><td><c:choose><c:when test="${user.status eq 'ACTIVE'}"><span class="badge text-bg-success">ACTIVE</span></c:when><c:when test="${user.status eq 'LOCKED'}"><span class="badge text-bg-danger">LOCKED</span></c:when><c:otherwise><span class="badge text-bg-secondary">INACTIVE</span></c:otherwise></c:choose></td><td><c:out value="${user.createdAt}" /></td><td class="text-end pe-4"><c:choose><c:when test="${user.status eq 'LOCKED'}"><form method="post" action="${pageContext.request.contextPath}/admin/users/status" class="d-inline"><input type="hidden" name="userId" value="${user.id}"><input type="hidden" name="status" value="ACTIVE"><button class="btn btn-sm btn-success" type="submit"><i class="bi bi-unlock me-1"></i>Mở khóa</button></form></c:when><c:otherwise><form method="post" action="${pageContext.request.contextPath}/admin/users/status" class="d-inline"><input type="hidden" name="userId" value="${user.id}"><input type="hidden" name="status" value="LOCKED"><button class="btn btn-sm btn-outline-danger" type="submit"><i class="bi bi-lock me-1"></i>Khóa</button></form></c:otherwise></c:choose></td></tr></c:forEach>
                    <c:if test="${empty users}"><tr><td colspan="5" class="py-5 text-center text-muted"><i class="bi bi-people d-block fs-3 mb-2"></i>Không tìm thấy người dùng phù hợp.</td></tr></c:if>
                </tbody></table></div><c:if test="${not empty page and page.totalPages gt 1}"><nav class="p-3 border-top" aria-label="Phân trang người dùng"><ul class="pagination pagination-sm mb-0 justify-content-end"><c:forEach begin="1" end="${page.totalPages}" var="p"><li class="page-item ${p eq page.currentPage ? 'active' : ''}"><a class="page-link" href="${pageContext.request.contextPath}/admin/users?page=${p}&keyword=${param.keyword}&role=${param.role}&status=${param.status}">${p}</a></li></c:forEach></ul></nav></c:if></section>
            </div>
        </main>
    </div>
</div>
<jsp:include page="/WEB-INF/views/common/footer.jsp" />
